### ISSUE TITLE
Error: "Unable to open tar in WASM memory" using en-model.tgz

### ISSUE THREAD

**Issue by jakespracher** [msqr1/Vosklet#6]
Getting this using en-model.tgz served from my webserver with the latest

https://github.com/msqr1/Vosklet/blob/ef010940bc0fe54587e1c88503219e7848fd3fa5/src/genericModel.cc#L14

**Comment by msqr1** [comment]
To clear the saved model a d for easy testing, you would want to use OPFS explorer. Regarding testing the model with correct content encoding response header, I find it literally impossible if I don't have a test webserver, because I can't add the response header for browser to decompress. You can look at my newest commit, and found that I have to keep the old manual decompression for the examples to work.
